# Generated by Django 2.2.5 on 2019-10-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remaind', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='remaindtbl',
        ),
    ]
