# Generated by Django 2.2.5 on 2019-10-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remaind', '0002_auto_20191012_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='remaindtbl',
            name='name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
