# Generated by Django 2.2.5 on 2019-10-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remaind', '0003_remaindtbl_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=20)),
                ('email', models.CharField(default=0, max_length=20)),
                ('password', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
